# Traefik installation with DDNS allowlist plugin
experimental:
  plugins:
    ddns-allowlist:
      moduleName: "github.com/taskmedia/ddns-allowlist"
      version: v1.5.1

globalArguments:
- "--global.checknewversion=false"
- "--global.sendanonymoususage=false"

ingressRoute:
  dashboard:
    enabled: true

logs:
  general:
    level: DEBUG
