# Traefik installation with DDNS whitelist plugin
experimental:
  plugins:
    ddns-whitelist:
      moduleName: "github.com/taskmedia/ddns-whitelist"
      version: v2.0.0

globalArguments:
- "--global.checknewversion=false"
- "--global.sendanonymoususage=false"

ingressRoute:
  dashboard:
    enabled: true

logs:
  general:
    level: DEBUG
